
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 6;
  public static final int POR = 29;
  public static final int CHAR = 15;
  public static final int GE = 36;
  public static final int CASE = 53;
  public static final int REM = 44;
  public static final int INT = 13;
  public static final int IMPLICA = 41;
  public static final int FOR = 47;
  public static final int CP = 5;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int ELSEIF = 52;
  public static final int LT = 33;
  public static final int CARACTER = 23;
  public static final int OR = 38;
  public static final int BOOL = 19;
  public static final int DIV = 30;
  public static final int ASIGNA = 40;
  public static final int CC = 7;
  public static final int IF = 45;
  public static final int ID = 20;
  public static final int LE = 35;
  public static final int EOF = 0;
  public static final int U_MINUS = 17;
  public static final int RETURN = 57;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int CADENA = 24;
  public static final int ADD = 43;
  public static final int MENOS = 28;
  public static final int NEQ = 32;
  public static final int BREAK = 56;
  public static final int VOID = 18;
  public static final int EQ = 31;
  public static final int CLL = 3;
  public static final int SWITCH = 54;
  public static final int UNION = 42;
  public static final int ELSE = 51;
  public static final int NUM_REAL = 22;
  public static final int PUNTO = 10;
  public static final int WHILE = 46;
  public static final int DEFAULT = 55;
  public static final int FLOAT = 14;
  public static final int NUM_ENTERO = 21;
  public static final int STRING = 16;
  public static final int ALL = 2;
  public static final int FALSE = 25;
  public static final int AP = 4;
  public static final int GT = 34;
  public static final int DP = 11;
  public static final int LENGTH = 50;
  public static final int PRINT = 49;
  public static final int DO = 48;
  public static final int SET = 12;
  public static final int PYC = 8;
  public static final int MAS = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "AC",
  "CC",
  "PYC",
  "COMA",
  "PUNTO",
  "DP",
  "SET",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "U_MINUS",
  "VOID",
  "BOOL",
  "ID",
  "NUM_ENTERO",
  "NUM_REAL",
  "CARACTER",
  "CADENA",
  "FALSE",
  "TRUE",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "AND",
  "OR",
  "NOT",
  "ASIGNA",
  "IMPLICA",
  "UNION",
  "ADD",
  "REM",
  "IF",
  "WHILE",
  "FOR",
  "DO",
  "PRINT",
  "LENGTH",
  "ELSE",
  "ELSEIF",
  "CASE",
  "SWITCH",
  "DEFAULT",
  "BREAK",
  "RETURN"
  };
}

